/* soapServer.cpp
   Generated by gSOAP 2.8.23 from test.hpp

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.23 2015-11-06 13:32:36 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:AccountAuth"))
		return soap_serve_ns1__AccountAuth(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SendWord"))
		return soap_serve_ns1__SendWord(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetWord"))
		return soap_serve_ns1__GetWord(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:PlayWord"))
		return soap_serve_ns1__PlayWord(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__AccountAuth(struct soap *soap)
{	struct ns1__AccountAuth soap_tmp_ns1__AccountAuth;
	struct ns1__AccountAuthResponse _param_1;
	soap_default_ns1__AccountAuthResponse(soap, &_param_1);
	soap_default_ns1__AccountAuth(soap, &soap_tmp_ns1__AccountAuth);
	if (!soap_get_ns1__AccountAuth(soap, &soap_tmp_ns1__AccountAuth, "ns1:AccountAuth", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__AccountAuth(soap, soap_tmp_ns1__AccountAuth._email, soap_tmp_ns1__AccountAuth._pass, _param_1);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__AccountAuthResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__AccountAuthResponse(soap, &_param_1, "ns1:AccountAuthResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__AccountAuthResponse(soap, &_param_1, "ns1:AccountAuthResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__SendWord(struct soap *soap)
{	struct ns1__SendWord soap_tmp_ns1__SendWord;
	struct ns1__SendWordResponse _param_2;
	soap_default_ns1__SendWordResponse(soap, &_param_2);
	soap_default_ns1__SendWord(soap, &soap_tmp_ns1__SendWord);
	if (!soap_get_ns1__SendWord(soap, &soap_tmp_ns1__SendWord, "ns1:SendWord", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__SendWord(soap, soap_tmp_ns1__SendWord._word_USCOREa, soap_tmp_ns1__SendWord._word_USCOREb, soap_tmp_ns1__SendWord._lang_USCOREa, soap_tmp_ns1__SendWord._lang_USCOREb, _param_2);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__SendWordResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SendWordResponse(soap, &_param_2, "ns1:SendWordResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SendWordResponse(soap, &_param_2, "ns1:SendWordResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__GetWord(struct soap *soap)
{	struct ns1__GetWord soap_tmp_ns1__GetWord;
	struct ns1__GetWordResponse _param_3;
	soap_default_ns1__GetWordResponse(soap, &_param_3);
	soap_default_ns1__GetWord(soap, &soap_tmp_ns1__GetWord);
	if (!soap_get_ns1__GetWord(soap, &soap_tmp_ns1__GetWord, "ns1:GetWord", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__GetWord(soap, soap_tmp_ns1__GetWord._range, soap_tmp_ns1__GetWord._opt, _param_3);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__GetWordResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetWordResponse(soap, &_param_3, "ns1:GetWordResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetWordResponse(soap, &_param_3, "ns1:GetWordResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__PlayWord(struct soap *soap)
{	struct ns1__PlayWord soap_tmp_ns1__PlayWord;
	struct ns1__PlayWordResponse _param_4;
	soap_default_ns1__PlayWordResponse(soap, &_param_4);
	soap_default_ns1__PlayWord(soap, &soap_tmp_ns1__PlayWord);
	if (!soap_get_ns1__PlayWord(soap, &soap_tmp_ns1__PlayWord, "ns1:PlayWord", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__PlayWord(soap, soap_tmp_ns1__PlayWord._id, soap_tmp_ns1__PlayWord._value, soap_tmp_ns1__PlayWord._direction, _param_4);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__PlayWordResponse(soap, &_param_4);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__PlayWordResponse(soap, &_param_4, "ns1:PlayWordResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__PlayWordResponse(soap, &_param_4, "ns1:PlayWordResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
