/* soapClient.cpp
   Generated by gSOAP 2.8.23 from test.hpp

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.23 2015-10-30 14:54:04 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GetComplexType(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__GetComplexTypeResponse &_param_1)
{	struct ns1__GetComplexType soap_tmp_ns1__GetComplexType;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://brzeszczot.net/open/php-wsdl-2.3/demo.php";
	if (soap_action == NULL)
		soap_action = "http://brzeszczot.net/open/php-wsdl-2.3/GetComplexType";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__GetComplexType(soap, &soap_tmp_ns1__GetComplexType);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetComplexType(soap, &soap_tmp_ns1__GetComplexType, "ns1:GetComplexType", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetComplexType(soap, &soap_tmp_ns1__GetComplexType, "ns1:GetComplexType", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_1)
		return soap_closesock(soap);
	soap_default_ns1__GetComplexTypeResponse(soap, &_param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__GetComplexTypeResponse(soap, &_param_1, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__PrintComplexType(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ComplexTypeDemo *obj, std::string &return_)
{	struct ns1__PrintComplexType soap_tmp_ns1__PrintComplexType;
	struct ns1__PrintComplexTypeResponse *soap_tmp_ns1__PrintComplexTypeResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://brzeszczot.net/open/php-wsdl-2.3/demo.php";
	if (soap_action == NULL)
		soap_action = "http://brzeszczot.net/open/php-wsdl-2.3/PrintComplexType";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__PrintComplexType.obj = obj;
	soap_serializeheader(soap);
	soap_serialize_ns1__PrintComplexType(soap, &soap_tmp_ns1__PrintComplexType);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__PrintComplexType(soap, &soap_tmp_ns1__PrintComplexType, "ns1:PrintComplexType", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__PrintComplexType(soap, &soap_tmp_ns1__PrintComplexType, "ns1:PrintComplexType", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&return_)
		return soap_closesock(soap);
	soap_default_std__string(soap, &return_);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__PrintComplexTypeResponse = soap_get_ns1__PrintComplexTypeResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__PrintComplexTypeResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return_ = soap_tmp_ns1__PrintComplexTypeResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ComplexTypeArrayDemo(struct soap *soap, const char *soap_endpoint, const char *soap_action, ComplexTypeDemoArray *arr, struct ns1__ComplexTypeArrayDemoResponse &_param_2)
{	struct ns1__ComplexTypeArrayDemo soap_tmp_ns1__ComplexTypeArrayDemo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://brzeszczot.net/open/php-wsdl-2.3/demo.php";
	if (soap_action == NULL)
		soap_action = "http://brzeszczot.net/open/php-wsdl-2.3/ComplexTypeArrayDemo";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ComplexTypeArrayDemo.arr = arr;
	soap_serializeheader(soap);
	soap_serialize_ns1__ComplexTypeArrayDemo(soap, &soap_tmp_ns1__ComplexTypeArrayDemo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ComplexTypeArrayDemo(soap, &soap_tmp_ns1__ComplexTypeArrayDemo, "ns1:ComplexTypeArrayDemo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ComplexTypeArrayDemo(soap, &soap_tmp_ns1__ComplexTypeArrayDemo, "ns1:ComplexTypeArrayDemo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_2)
		return soap_closesock(soap);
	soap_default_ns1__ComplexTypeArrayDemoResponse(soap, &_param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__ComplexTypeArrayDemoResponse(soap, &_param_2, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SayHello(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string name, std::string &return_)
{	struct ns1__SayHello soap_tmp_ns1__SayHello;
	struct ns1__SayHelloResponse *soap_tmp_ns1__SayHelloResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://brzeszczot.net/open/php-wsdl-2.3/demo.php";
	if (soap_action == NULL)
		soap_action = "http://brzeszczot.net/open/php-wsdl-2.3/SayHello";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__SayHello.name = name;
	soap_serializeheader(soap);
	soap_serialize_ns1__SayHello(soap, &soap_tmp_ns1__SayHello);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SayHello(soap, &soap_tmp_ns1__SayHello, "ns1:SayHello", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SayHello(soap, &soap_tmp_ns1__SayHello, "ns1:SayHello", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&return_)
		return soap_closesock(soap);
	soap_default_std__string(soap, &return_);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__SayHelloResponse = soap_get_ns1__SayHelloResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__SayHelloResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return_ = soap_tmp_ns1__SayHelloResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DemoMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__DemoMethodResponse &_param_3)
{	struct ns1__DemoMethod soap_tmp_ns1__DemoMethod;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://brzeszczot.net/open/php-wsdl-2.3/demo.php";
	if (soap_action == NULL)
		soap_action = "http://brzeszczot.net/open/php-wsdl-2.3/DemoMethod";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__DemoMethod(soap, &soap_tmp_ns1__DemoMethod);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__DemoMethod(soap, &soap_tmp_ns1__DemoMethod, "ns1:DemoMethod", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__DemoMethod(soap, &soap_tmp_ns1__DemoMethod, "ns1:DemoMethod", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_3)
		return soap_closesock(soap);
	soap_default_ns1__DemoMethodResponse(soap, &_param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__DemoMethodResponse(soap, &_param_3, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
