/* soapMbsLookupSoapBindingProxy.h
   Generated by gSOAP 2.8.8 from wsd.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapMbsLookupSoapBindingProxy_H
#define soapMbsLookupSoapBindingProxy_H
#include "soapH.h"
class MbsLookupSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'MbsLookupSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	MbsLookupSoapBinding()
	{ soap = soap_new(); endpoint = "http://www.barnesandnobleinc.com/mbs/services/MbsLookup"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://xml.apache.org/xml-soap", NULL, NULL},
	{"ns3", "http://data.locator.bninc", NULL, NULL},
	{"ns4", "urn:MbsLookup", NULL, NULL},
	{"ns5", "http://ws.locator.bninc", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~MbsLookupSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getStatus' of service 'MbsLookupSoapBinding' and return error code (or SOAP_OK)
	virtual int ns5__getStatus(std::string &getStatusReturn) { return soap ? soap_call_ns5__getStatus(soap, endpoint, NULL, getStatusReturn) : SOAP_EOM; };
	/// Invoke 'findStores' of service 'MbsLookupSoapBinding' and return error code (or SOAP_OK)
	virtual int ns5__findStores(std::string _zipcode, struct ns5__findStoresResponse &_param_1) { return soap ? soap_call_ns5__findStores(soap, endpoint, NULL, _zipcode, _param_1) : SOAP_EOM; };
};
#endif
